stages:
  - build
  - docker
  - deploy

variables:
  IMAGE_TAG: store-app:latest

build:
  stage: build
  tags:
    - local
  image: gradle:8.4-jdk17
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/Store-0.0.1-SNAPSHOT.jar

docker-build:
  stage: docker
  tags:
    - local
  script:
    - docker build -t $IMAGE_TAG .
  dependencies:
    - build

deploy:
  stage: deploy
  tags:
    - local
  script:
    - helm upgrade --install store ./store-app --namespace store --create-namespace --set image.repository=store-app --set image.tag=latest
  only:
    - master