stages:
  - build
  - docker
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: gradle:8.4-jdk17
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/Store-0.0.1-SNAPSHOT.jar

docker-build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - build

deploy:
  stage: deploy
  image:
    name: lachlanevenson/k8s-helm:latest
    entrypoint: [""]
  script:
    - |
      export KUBECONFIG=$KUBECONFIG_FILE
      helm upgrade --install store ./store-app \
        --namespace store \
        --create-namespace \
        --set image.repository=store-app \
        --set image.tag=latest
  only:
    - master