version: "3.9"
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis-for-store"
    ports:
      - "6379:6379"
      - "8001:8001"
  postgres:
    image: "postgres:latest"
    container_name: "postgres-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
