apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-app.fullname" . }}
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "store-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "store-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-redis
          image: busybox:1.31.1
          command: [
            'sh',
            '-c',
            'until nc -z {{ .Values.appConfig.redis.host }} {{ .Values.appConfig.redis.port }}; do echo "Waiting for Redis..."; sleep 2; done;'
          ]
        - name: wait-for-postgres
          image: busybox:1.31.1
          command: [
            'sh',
            '-c',
            'until nc -z {{ .Values.appConfig.postgres.host }} {{ .Values.appConfig.postgres.port }}; do echo "Waiting for PostgreSQL..."; sleep 2; done;'
          ]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: SERVER_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: POSTGRES_DB
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "store-app.fullname" . }}-config
                  key: REDIS_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-app.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-app.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}