{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-app.fullname" . }}-secret
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ required "The 'secrets.postgresql.username' parameter is required" .Values.secrets.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "The 'secrets.postgresql.password' parameter is required" .Values.secrets.postgresql.password | b64enc | quote }}
{{- end }}
