apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "store-app.fullname" . }}-monitor
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      {{- include "store-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}